# Generated by Anaconda 40.22.3.36
# Generated by pykickstart v3.52.10
#version=RHEL10
text
authselect select custom/hardening with-faillock with-pwhistory without-nullok

%addon com_redhat_kdump --disable

%end

# Keyboard layouts
keyboard --vckeymap=us --xlayouts='us'
# System language
lang en_US.UTF-8

# Network information
network  --bootproto=static --device=ens192 --gateway=10.31.1.1 --ip=10.31.1.245 --nameserver=10.31.1.1 --netmask=255.255.255.0 --noipv6 --activate --ipv4-dns-search=ve.ex-cle.local
network  --hostname=template-cs10.ve.ex-cle.local

# Use network installation
url --url="https://mirror.stream.centos.org/10-stream/BaseOS/x86_64/os/"
repo --name="CentOS-BaseOS"    --baseurl=https://mirror.stream.centos.org/10-stream/BaseOS/x86_64/os/
repo --name="CentOS-AppStream" --baseurl=https://mirror.stream.centos.org/10-stream/AppStream/x86_64/os/
repo --name="EPEL"             --baseurl=https://dl.fedoraproject.org/pub/epel/10/Everything/x86_64/
repo --name="Docker"           --baseurl=https://download.docker.com/linux/rhel/10/x86_64/stable/

%packages
@^minimal-environment
@standard
aide
audit
firewalld
libselinux
nftables
openscap
openscap-scanner
rsyslog
scap-security-guide
sudo
vim
nc
docker-ce
docker-ce-cli
containerd.io
docker-buildx-plugin
docker-compose-plugin
git
open-vm-tools
dnf-plugins-core
cloud-init
cloud-utils-growpart
qemu-guest-agent
-avahi
-bind
-cups
-cyrus-imapd
-dhcp-server
-dnsmasq
-dovecot
-ftp
-gdm
-httpd
-mcstrans
-net-snmp
-nginx
-openldap-clients
-rsync-daemon
-samba
-setroubleshoot
-squid
-telnet
-telnet-server
-tftp
-tftp-server
-vsftpd
-xorg-x11-server-common
-docker
-docker-client
-docker-client-latest
-docker-common
-docker-latest
-docker-latest-logrotate
-docker-logrotate
-docker-engine

%end

# Accept Eula
eula --agreed

# Run the Setup Agent on first boot
firstboot --disable

# Generated using Blivet version 3.6.0
ignoredisk --only-use=sda

# Partition clearing information
zerombr
clearpart --all --initlabel --drives=sda

# Disk partitioning information
part /boot --fstype="xfs" --ondisk=sda --size=1024
part /boot/efi --fstype="efi" --ondisk=sda --size=1024 --fsoptions="umask=0077,shortname=winnt"
part pv.281 --fstype="lvmpv" --ondisk=sda --size=1 --grow
volgroup centos --pesize=4096 pv.281
logvol swap --fstype="swap" --size=4096 --name=swap --vgname=centos
logvol / --fstype="xfs" --percent=15 --name=root --vgname=centos
logvol /tmp --fstype="xfs" --percent=5 --name=tmp --vgname=centos
logvol /home --fstype="xfs" --percent=5 --name=home --vgname=centos
logvol /var --fstype="xfs" --percent=10 --name=var --vgname=centos
logvol /var/log --fstype="xfs" --percent=10 --name=var_log --vgname=centos
logvol /var/log/audit --fstype="xfs" --percent=10 --name=var_log_audit --vgname=centos
logvol /var/lib --fstype="xfs" --percent=30 --name=var_lib --vgname=centos
logvol /opt --fstype="xfs" --percent=10 --name=opt --vgname=centos

# System timezone
timesource --ntp-server=time1.google.com
timesource --ntp-server=time2.google.com
timesource --ntp-server=time3.google.com
timesource --ntp-server=time4.google.com
timezone America/Caracas --utc

# Root password
rootpw --iscrypted $6$KxvmPKIPJSPeLMal$oOfIbzXioNtjjzZxDyqEJwvIKSojnQ4B/ywHW1HhH85CK.tmT4BpxtMCKShTzhaWpEH0I/Hxg1Ccs9.26ZbRR1
user --name=excle --password=$6$jNu1EkYYulv6zzGr$1BJzVUddsojiWUu0bw5FQJxYGgf7f8bKv/t/LaNU5/7QLzo.WsaXUOp6SIWWj5YYEEcOpCwGJjUW01fnNxDCE0 --iscrypted --gecos="ExCle Administrative User"  --uid=1000 --gid=1000

%post --log=/root/ks-post.log
### Update DB
/usr/sbin/updatedb

### Enable Services
for SERVICE in vmtoolsd firewalld NetworkManager
do
    systemctl enable --now $SERVICE
done

### PAM and DNF Configuration
sed -i 's/^enabled.*$/enabled=0/g' /etc/dnf/pluginconf.d/product-id.conf || true
sed -i 's/^enabled.*$/enabled=0/g' /etc/dnf/pluginconf.d/subscription-manager.conf || true
sed -i '/^auth.*required.*pam\Swheel\.so.*$/ s/^/#/' /etc/pam.d/su || true
sed -i '/^#auth.*sufficient.*pam\Swheel\.so.*$/ s/^#//' /etc/pam.d/su || true

### Security Mount Points in fstab
grep -q '/var/tmp' /etc/fstab || echo '/tmp /var/tmp none rw,nodev,noexec,nosuid,bind 0 0' >> /etc/fstab
grep -q 'proc /proc' /etc/fstab || echo 'proc /proc proc defaults,hidepid=2 0 0' >> /etc/fstab
grep -q 'devtmpfs /dev' /etc/fstab || echo 'devtmpfs /dev devtmpfs mode=0755,noexec,nosuid 0 0' >> /etc/fstab
grep -q 'tmpfs /dev/shm' /etc/fstab || echo 'tmpfs /dev/shm tmpfs defaults,relatime,nodev,noexec,nosuid 0 0' >> /etc/fstab
for MOUNT_POINT in /var/tmp /proc /dev /dev/shm
do
    if [[ $MOUNT_POINT == "/var/tmp" ]]
    then
        rm -rf "${MOUNT_POINT}/*"
    fi
    mount -o remount $MOUNT_POINT || true
done

### GRUB Password Configuration
cat << 'EOF' > /etc/grub.d/01_users
#!/bin/sh
cat << 'GRUB_CONF'
set superusers="excle"
password_pbkdf2 excle grub.pbkdf2.sha512.10000.3356BEC0FC70C29AEA8C70B1671E4153D9CD358D921A5007D3D33A1D09217BA7F7505FEBD6579CC0331B9791F3013458BC98DA656DBCBA4E1CD494FB9D87B939.A790353441D81053C138E8979CD1740767DE5ACB965596E71FD96FFBFEFA1B1A06416C1A1B51CE53482CFF92DEBD024108E13C733FE7A281E50C8FC757BE0567
GRUB_CONF
EOF
chmod +x /etc/grub.d/01_users
grub2-mkconfig -o /boot/grub2/grub.cfg

### Docker group and basic configuration
for USER in excle; do usermod -aG docker $USER || true; done
cat << EOF > /etc/docker/daemon.json
{
    "log-driver": "journald",
    "log-opts": {
        "tag": "{{.Name}}"
    },
    "ipv6": false,
    "default-address-pools": [
        { "base": "10.80.0.0/16", "size": 24 }
    ]
}

EOF

### SSH Configuration
cat << EOF > /etc/ssh/sshd_config.d/00-basic.conf
PasswordAuthentication yes

EOF
chmod 0644 /etc/ssh/sshd_config.d/*

### Sudoers Configuration
cat << EOF > /etc/sudoers.d/00_admin_users
excle ALL=(ALL:ALL) NOPASSWD:ALL

EOF
chmod 0440 /etc/sudoers.d/00_admin_users
dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
dnf install -y epel-release

%end

reboot
